name = "enready-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "STATS"
id = "edd329ecfc8646f9b7215da4bab70138"

[[d1_databases]]
binding = "DB"
database_name = "enready-db"
database_id = "735ef8cd-dcd6-4420-8c15-f4ffe8c57533"
